import { google } from '@ai-sdk/google'
import { generateObject } from 'ai'
import { z } from 'zod'
import type { Retailer, ProductData, DealAnalysis } from '@/types'

// Schema for retailer URLs generated by Gemini
const retailerUrlsSchema = z.object({
  retailers: z.array(
    z.object({
      name: z.string().describe('Name of the retailer'),
      url: z.string().url().describe('Direct search URL for the Lego set')
    })
  )
})

// Schema for deal analysis
const dealAnalysisSchema = z.object({
  bestRetailer: z.string().describe('Name of the best retailer to buy from'),
  reason: z.string().describe('2-3 sentence explanation of why this is the best deal'),
  totalCost: z.string().describe('Total cost including shipping, formatted with currency'),
  savings: z.string().describe('Amount saved compared to alternatives'),
  alternativeOptions: z
    .array(
      z.object({
        retailer: z.string(),
        cost: z.string(),
        pros: z.array(z.string())
      })
    )
    .optional()
    .describe('Alternative purchase options')
})

/**
 * Generate retailer search URLs using Gemini
 */
export async function generateRetailerUrls(legoSetName: string): Promise<Retailer[]> {
  const model = google('gemini-2.0-flash-exp')

  const prompt = `You are a Lego shopping expert. Generate 15 specific product search URLs for finding "${legoSetName}" Lego set.

Include these retailers and create direct search URLs that would find this specific set:
1. LEGO.com official store (lego.com/en-us/search)
2. Amazon US (amazon.com/s)
3. Target (target.com/s)
4. Walmart (walmart.com/search)
5. BrickLink (bricklink.com/v2/search.page)
6. Zavvi (zavvi.com)
7. Toys R Us (toysrus.com)
8. Barnes & Noble (barnesandnoble.com)
9. Kohls (kohls.com)
10. Best Buy (bestbuy.com)
11. GameStop (gamestop.com)
12. Smyths Toys UK (smythstoys.com)
13. John Lewis UK (johnlewis.com)
14. Argos UK (argos.co.uk)
15. Entertainment Earth (entertainmentearth.com)

For each retailer:
- Use their actual search URL format
- Include the Lego set name/number in the search query
- Make the URL valid and properly encoded

Return exactly 15 retailers with their search URLs.`

  const { object } = await generateObject({
    model,
    schema: retailerUrlsSchema,
    prompt
  })

  return object.retailers
}

/**
 * Analyze search results and find the best deal using Gemini
 */
export async function analyzeBestDeal(
  legoSetName: string,
  maxBudget: number,
  results: ProductData[]
): Promise<DealAnalysis> {
  const model = google('gemini-2.0-flash-exp')

  // Filter to only in-stock results
  const inStockResults = results.filter(r => r.inStock)

  if (inStockResults.length === 0) {
    return {
      bestRetailer: 'None',
      reason:
        'Unfortunately, this Lego set is currently out of stock at all searched retailers. Consider setting up stock alerts or checking back later.',
      totalCost: 'N/A',
      savings: 'N/A',
      alternativeOptions: []
    }
  }

  const prompt = `Analyze these Lego set search results and recommend the best deal:

Set: ${legoSetName}
Budget: $${maxBudget}

Search Results (in-stock only):
${JSON.stringify(inStockResults, null, 2)}

Consider these factors:
1. In-stock availability (must be in stock)
2. Total cost (price + shipping)
3. Retailer reputation and reliability
4. Shipping speed (prefer US retailers for faster shipping)

If the best option exceeds the budget, still recommend it but mention it in the reason.

Provide your analysis with the best retailer recommendation.`

  const { object } = await generateObject({
    model,
    schema: dealAnalysisSchema,
    prompt
  })

  return object
}

/**
 * Format price for display
 */
export function formatPrice(price: string, currency: string = 'USD'): string {
  const numPrice = parseFloat(price.replace(/[^0-9.]/g, ''))
  if (isNaN(numPrice)) return price

  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency
  }).format(numPrice)
}
