/**
 * Export utilities for CostLens reports.
 */

/**
 * Triggers a JSON file download in the browser.
 */
export function exportAsJson(report) {
  if (!report) return;
  const targetName = (report.target?.name || "unknown").replace(/[^a-zA-Z0-9]/g, "_").toLowerCase();
  const date = new Date().toISOString().slice(0, 10);
  const filename = `costlens-${targetName}-${date}.json`;
  const blob = new Blob([JSON.stringify(report, null, 2)], { type: "application/json" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Builds a plain-text summary from the report and copies to clipboard.
 * Returns true on success, false on failure.
 */
export async function copyTextSummary(report) {
  if (!report) return false;
  const lines = [];
  const hr = "─".repeat(50);

  lines.push(`CostLens Report: ${report.target?.name || "Unknown"}`);
  lines.push(`URL: ${report.target?.url || "N/A"}`);
  lines.push(`Date: ${report.scannedAt ? new Date(report.scannedAt).toLocaleDateString() : "N/A"}`);
  lines.push(hr);

  // Executive Summary
  if (report.executiveSummary?.summary) {
    lines.push("");
    lines.push("EXECUTIVE SUMMARY");
    lines.push(`Verdict: ${report.executiveSummary.verdictLabel || "N/A"}`);
    lines.push(report.executiveSummary.summary);
    if (report.executiveSummary.keyFindings?.length > 0) {
      lines.push("");
      lines.push("Key Findings:");
      report.executiveSummary.keyFindings.forEach((f) => lines.push(`  • ${f}`));
    }
    lines.push(hr);
  }

  // Infrastructure
  const infra = report.infraCost;
  if (infra) {
    lines.push("");
    lines.push("INFRASTRUCTURE COST (Their Cost)");
    lines.push(`  Monthly Estimate: $${fmt(infra.monthlyEstimate?.low)} – $${fmt(infra.monthlyEstimate?.high)}`);
    lines.push(`  Gross Margin: ${infra.grossMargin?.low}% – ${infra.grossMargin?.high}%`);
    lines.push(`  Per-User Cost: $${infra.perUserEstimate?.low} – $${infra.perUserEstimate?.high}/user/mo`);
    lines.push(`  Confidence: ${infra.confidence?.overall || 0}% (${infra.confidence?.level || "low"})`);
  }

  // Build
  const build = report.buildCost;
  if (build) {
    lines.push("");
    lines.push("BUILD COST");
    lines.push(`  Total Estimate: $${fmt(build.totalEstimate?.low)} – $${fmt(build.totalEstimate?.high)}`);
    lines.push(`  Timeline: ${build.timeEstimate?.low} – ${build.timeEstimate?.high} months`);
    lines.push(`  Team Size: ${build.teamSize?.min} – ${build.teamSize?.max} engineers`);
    lines.push(`  Confidence: ${build.confidence?.overall || 0}% (${build.confidence?.level || "low"})`);
  }

  // Buyer
  const buyer = report.buyerCost;
  if (buyer?.plans?.length > 0) {
    lines.push("");
    lines.push("BUYER COST (Your Cost)");
    buyer.plans.forEach((p) => {
      lines.push(`  ${p.name}: Listed ${p.listed}, Actual ${p.actualMonthly}`);
    });
    lines.push(`  Confidence: ${buyer.confidence?.overall || 0}% (${buyer.confidence?.level || "low"})`);
  }

  // Risk
  const risk = report.riskProfile;
  if (risk) {
    lines.push("");
    lines.push("RISK PROFILE");
    lines.push(`  Overall Risk: ${risk.overallRiskLevel || "N/A"}`);
    lines.push(`  Security Score: ${risk.securityScore || 0}/100`);
    lines.push(`  Trackers: ${risk.trackerSummary?.total || 0}`);
  }

  // Recommendations
  if (report.executiveSummary?.recommendations?.length > 0) {
    lines.push("");
    lines.push(hr);
    lines.push("RECOMMENDATIONS");
    report.executiveSummary.recommendations.forEach((r) => {
      lines.push(`  [${r.priority?.toUpperCase()}] ${r.title}: ${r.detail}`);
    });
  }

  lines.push("");
  lines.push(hr);
  lines.push("Generated by CostLens · Data is estimated, not financial advice.");

  const text = lines.join("\n");
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    return false;
  }
}

function fmt(n) {
  if (n == null || !Number.isFinite(Number(n))) return "N/A";
  return Number(n).toLocaleString();
}
