// --- Source Platform ---
export type SourcePlatform = 'github' | 'stackoverflow';

// --- OpenRouter Analysis Output ---
export interface CodeAnalysis {
  language: string;
  libraries: string[];
  apis: string[];
  patterns: string[];
}

// --- Search Query (generated by OpenRouter) ---
export interface SearchQuery {
  query: string;
  target: 'github' | 'stackoverflow';
  heuristic: string;
}

// --- Stack Exchange API item shape ---
export interface StackExchangeItem {
  question_id: number;
  title: string;
  tags: string[];
  score: number;
  answer_count: number;
  is_answered: boolean;
  link: string;
  body_excerpt?: string;
}

// --- Search Result (from indexed APIs) ---
export interface SearchResult {
  platform: SourcePlatform;
  url: string;
  title: string;
  snippet: string;
  stars?: number;
  language?: string;
  score?: number;
  answerCount?: number;
  tags?: string[];
  isAnswered?: boolean;
  apiData?: StackExchangeItem;
}

// --- Code Snippet extracted by agents ---
export interface CodeSnippet {
  code: string;
  language: string;
  context: string;
}

// --- Extracted Reference Data (from Mino agents) ---
export interface ReferenceData {
  sourceUrl: string;
  platform: SourcePlatform;
  title: string;
  relevanceScore: number;
  alignmentExplanation: string;
  codeSnippets: CodeSnippet[];
  repoName?: string;
  repoDescription?: string;
  stars?: number;
  repoLanguage?: string;
  readmeExcerpt?: string;
  questionTitle?: string;
  votes?: number;
  answerSnippets?: string[];
  tags?: string[];
  isAccepted?: boolean;
}

// --- Agent State ---
export type AgentStatus =
  | 'connecting'
  | 'navigating'
  | 'extracting'
  | 'reasoning'
  | 'complete'
  | 'error';

export interface AgentStep {
  message: string;
  timestamp: number;
}

export interface ReferenceAgentState {
  id: string;
  url: string;
  platform: SourcePlatform;
  status: AgentStatus;
  currentStep: string;
  steps: AgentStep[];
  streamingUrl?: string;
  result?: ReferenceData;
  error?: string;
  startedAt?: number;
  completedAt?: number;
}

// --- App State ---
export type AppPhase =
  | 'input'
  | 'analyzing'
  | 'searching'
  | 'extracting'
  | 'complete';

export interface AppState {
  phase: AppPhase;
  userCode: string | null;
  analysis: CodeAnalysis | null;
  searchQueries: SearchQuery[];
  searchResults: SearchResult[];
  agents: Record<string, ReferenceAgentState>;
  startedAt: number | null;
  completedAt: number | null;
}

// --- Reducer Actions ---
export type AppAction =
  | { type: 'START_ANALYSIS'; payload: { code: string } }
  | { type: 'ANALYSIS_COMPLETE'; payload: { analysis: CodeAnalysis; queries: SearchQuery[] } }
  | { type: 'SEARCH_COMPLETE'; payload: { results: SearchResult[] } }
  | { type: 'AGENT_CONNECTING'; payload: { id: string; url: string; platform: SourcePlatform } }
  | { type: 'AGENT_STEP'; payload: { id: string; step: string } }
  | { type: 'AGENT_STREAMING_URL'; payload: { id: string; streamingUrl: string } }
  | { type: 'AGENT_COMPLETE'; payload: { id: string; result: ReferenceData } }
  | { type: 'AGENT_ERROR'; payload: { id: string; error: string } }
  | { type: 'RESET' };

// --- Mino SSE types ---
export interface MinoSSEEvent {
  type?: string;
  status?: string;
  message?: string;
  purpose?: string;
  action?: string;
  resultJson?: unknown;
  streamingUrl?: string;
  step?: number;
  totalSteps?: number;
}

export interface MinoCallbacks {
  onStep: (event: MinoSSEEvent) => void;
  onStreamingUrl: (url: string) => void;
  onComplete: (result: unknown) => void;
  onError: (error: string) => void;
}

export interface MinoRequestConfig {
  url: string;
  goal: string;
}

// --- SSE Orchestration Events (API route -> client) ---
export type OrchestratorEventType =
  | 'analysis_complete'
  | 'search_complete'
  | 'agent_connecting'
  | 'agent_step'
  | 'agent_streaming_url'
  | 'agent_complete'
  | 'agent_error'
  | 'pipeline_complete'
  | 'pipeline_error';

export interface OrchestratorEvent {
  type: OrchestratorEventType;
  data: Record<string, unknown>;
}
